language: node_js
node_js:
  - "10"
  - "12"
jobs:
  include:
    - stage: tests
      script: npm run lint
    - stage: package generation
      name: babel package
      install:
        - npx gulp package:create -n babel-test
        - cd out/babel-test
        - npm run clean
    - stage:
      name: non-babel package
      install:
        - npx gulp package:create --nobabel -n non-babel-test
        - cd out/non-babel-test
        - npm run clean
